version: "3.8"
services:
  db:
    image: postgres:13.7
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  orm_test:
    build: .
    ports:
      - 3000:3000
    working_dir:
      /var/opt/orm_test
    command: ['bin/rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    env_file:
      .env
    tmpfs:
      - /var/opt/orm_test/tmp
    volumes: &yoshina_volumes
      - .:/var/opt/orm_test
      - bundle_volume:/var/opt/orm_test/vendor/bundle
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  db_volume:
  bundle_volume:
