// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TestDataColumns holds the columns for the "test_data" table.
	TestDataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "text", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TestDataTable holds the schema information for the "test_data" table.
	TestDataTable = &schema.Table{
		Name:       "test_data",
		Columns:    TestDataColumns,
		PrimaryKey: []*schema.Column{TestDataColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TestDataTable,
	}
)

func init() {
}
