// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"orm_test/ent/predicate"
	"orm_test/ent/testdata"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TestDataQuery is the builder for querying TestData entities.
type TestDataQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TestData
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TestDataQuery builder.
func (tdq *TestDataQuery) Where(ps ...predicate.TestData) *TestDataQuery {
	tdq.predicates = append(tdq.predicates, ps...)
	return tdq
}

// Limit adds a limit step to the query.
func (tdq *TestDataQuery) Limit(limit int) *TestDataQuery {
	tdq.limit = &limit
	return tdq
}

// Offset adds an offset step to the query.
func (tdq *TestDataQuery) Offset(offset int) *TestDataQuery {
	tdq.offset = &offset
	return tdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tdq *TestDataQuery) Unique(unique bool) *TestDataQuery {
	tdq.unique = &unique
	return tdq
}

// Order adds an order step to the query.
func (tdq *TestDataQuery) Order(o ...OrderFunc) *TestDataQuery {
	tdq.order = append(tdq.order, o...)
	return tdq
}

// First returns the first TestData entity from the query.
// Returns a *NotFoundError when no TestData was found.
func (tdq *TestDataQuery) First(ctx context.Context) (*TestData, error) {
	nodes, err := tdq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{testdata.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tdq *TestDataQuery) FirstX(ctx context.Context) *TestData {
	node, err := tdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TestData ID from the query.
// Returns a *NotFoundError when no TestData ID was found.
func (tdq *TestDataQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tdq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{testdata.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tdq *TestDataQuery) FirstIDX(ctx context.Context) int {
	id, err := tdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TestData entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TestData entity is found.
// Returns a *NotFoundError when no TestData entities are found.
func (tdq *TestDataQuery) Only(ctx context.Context) (*TestData, error) {
	nodes, err := tdq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{testdata.Label}
	default:
		return nil, &NotSingularError{testdata.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tdq *TestDataQuery) OnlyX(ctx context.Context) *TestData {
	node, err := tdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TestData ID in the query.
// Returns a *NotSingularError when more than one TestData ID is found.
// Returns a *NotFoundError when no entities are found.
func (tdq *TestDataQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tdq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{testdata.Label}
	default:
		err = &NotSingularError{testdata.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tdq *TestDataQuery) OnlyIDX(ctx context.Context) int {
	id, err := tdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TestDataSlice.
func (tdq *TestDataQuery) All(ctx context.Context) ([]*TestData, error) {
	if err := tdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tdq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tdq *TestDataQuery) AllX(ctx context.Context) []*TestData {
	nodes, err := tdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TestData IDs.
func (tdq *TestDataQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := tdq.Select(testdata.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tdq *TestDataQuery) IDsX(ctx context.Context) []int {
	ids, err := tdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tdq *TestDataQuery) Count(ctx context.Context) (int, error) {
	if err := tdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tdq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tdq *TestDataQuery) CountX(ctx context.Context) int {
	count, err := tdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tdq *TestDataQuery) Exist(ctx context.Context) (bool, error) {
	if err := tdq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tdq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tdq *TestDataQuery) ExistX(ctx context.Context) bool {
	exist, err := tdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TestDataQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tdq *TestDataQuery) Clone() *TestDataQuery {
	if tdq == nil {
		return nil
	}
	return &TestDataQuery{
		config:     tdq.config,
		limit:      tdq.limit,
		offset:     tdq.offset,
		order:      append([]OrderFunc{}, tdq.order...),
		predicates: append([]predicate.TestData{}, tdq.predicates...),
		// clone intermediate query.
		sql:    tdq.sql.Clone(),
		path:   tdq.path,
		unique: tdq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Text string `json:"text,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TestData.Query().
//		GroupBy(testdata.FieldText).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tdq *TestDataQuery) GroupBy(field string, fields ...string) *TestDataGroupBy {
	grbuild := &TestDataGroupBy{config: tdq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tdq.sqlQuery(ctx), nil
	}
	grbuild.label = testdata.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Text string `json:"text,omitempty"`
//	}
//
//	client.TestData.Query().
//		Select(testdata.FieldText).
//		Scan(ctx, &v)
func (tdq *TestDataQuery) Select(fields ...string) *TestDataSelect {
	tdq.fields = append(tdq.fields, fields...)
	selbuild := &TestDataSelect{TestDataQuery: tdq}
	selbuild.label = testdata.Label
	selbuild.flds, selbuild.scan = &tdq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a TestDataSelect configured with the given aggregations.
func (tdq *TestDataQuery) Aggregate(fns ...AggregateFunc) *TestDataSelect {
	return tdq.Select().Aggregate(fns...)
}

func (tdq *TestDataQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tdq.fields {
		if !testdata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tdq.path != nil {
		prev, err := tdq.path(ctx)
		if err != nil {
			return err
		}
		tdq.sql = prev
	}
	return nil
}

func (tdq *TestDataQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TestData, error) {
	var (
		nodes = []*TestData{}
		_spec = tdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TestData).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TestData{config: tdq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tdq *TestDataQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tdq.querySpec()
	_spec.Node.Columns = tdq.fields
	if len(tdq.fields) > 0 {
		_spec.Unique = tdq.unique != nil && *tdq.unique
	}
	return sqlgraph.CountNodes(ctx, tdq.driver, _spec)
}

func (tdq *TestDataQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := tdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (tdq *TestDataQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   testdata.Table,
			Columns: testdata.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: testdata.FieldID,
			},
		},
		From:   tdq.sql,
		Unique: true,
	}
	if unique := tdq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tdq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, testdata.FieldID)
		for i := range fields {
			if fields[i] != testdata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tdq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tdq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tdq *TestDataQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tdq.driver.Dialect())
	t1 := builder.Table(testdata.Table)
	columns := tdq.fields
	if len(columns) == 0 {
		columns = testdata.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tdq.sql != nil {
		selector = tdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tdq.unique != nil && *tdq.unique {
		selector.Distinct()
	}
	for _, p := range tdq.predicates {
		p(selector)
	}
	for _, p := range tdq.order {
		p(selector)
	}
	if offset := tdq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tdq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TestDataGroupBy is the group-by builder for TestData entities.
type TestDataGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tdgb *TestDataGroupBy) Aggregate(fns ...AggregateFunc) *TestDataGroupBy {
	tdgb.fns = append(tdgb.fns, fns...)
	return tdgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tdgb *TestDataGroupBy) Scan(ctx context.Context, v any) error {
	query, err := tdgb.path(ctx)
	if err != nil {
		return err
	}
	tdgb.sql = query
	return tdgb.sqlScan(ctx, v)
}

func (tdgb *TestDataGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range tdgb.fields {
		if !testdata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tdgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tdgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tdgb *TestDataGroupBy) sqlQuery() *sql.Selector {
	selector := tdgb.sql.Select()
	aggregation := make([]string, 0, len(tdgb.fns))
	for _, fn := range tdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tdgb.fields)+len(tdgb.fns))
		for _, f := range tdgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tdgb.fields...)...)
}

// TestDataSelect is the builder for selecting fields of TestData entities.
type TestDataSelect struct {
	*TestDataQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tds *TestDataSelect) Aggregate(fns ...AggregateFunc) *TestDataSelect {
	tds.fns = append(tds.fns, fns...)
	return tds
}

// Scan applies the selector query and scans the result into the given value.
func (tds *TestDataSelect) Scan(ctx context.Context, v any) error {
	if err := tds.prepareQuery(ctx); err != nil {
		return err
	}
	tds.sql = tds.TestDataQuery.sqlQuery(ctx)
	return tds.sqlScan(ctx, v)
}

func (tds *TestDataSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(tds.fns))
	for _, fn := range tds.fns {
		aggregation = append(aggregation, fn(tds.sql))
	}
	switch n := len(*tds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		tds.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		tds.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := tds.sql.Query()
	if err := tds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
