// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orm_test/ent/predicate"
	"orm_test/ent/testdata"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TestDataUpdate is the builder for updating TestData entities.
type TestDataUpdate struct {
	config
	hooks    []Hook
	mutation *TestDataMutation
}

// Where appends a list predicates to the TestDataUpdate builder.
func (tdu *TestDataUpdate) Where(ps ...predicate.TestData) *TestDataUpdate {
	tdu.mutation.Where(ps...)
	return tdu
}

// SetText sets the "text" field.
func (tdu *TestDataUpdate) SetText(s string) *TestDataUpdate {
	tdu.mutation.SetText(s)
	return tdu
}

// SetCreatedAt sets the "created_at" field.
func (tdu *TestDataUpdate) SetCreatedAt(t time.Time) *TestDataUpdate {
	tdu.mutation.SetCreatedAt(t)
	return tdu
}

// SetUpdatedAt sets the "updated_at" field.
func (tdu *TestDataUpdate) SetUpdatedAt(t time.Time) *TestDataUpdate {
	tdu.mutation.SetUpdatedAt(t)
	return tdu
}

// Mutation returns the TestDataMutation object of the builder.
func (tdu *TestDataUpdate) Mutation() *TestDataMutation {
	return tdu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tdu *TestDataUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tdu.hooks) == 0 {
		affected, err = tdu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TestDataMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tdu.mutation = mutation
			affected, err = tdu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tdu.hooks) - 1; i >= 0; i-- {
			if tdu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tdu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tdu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tdu *TestDataUpdate) SaveX(ctx context.Context) int {
	affected, err := tdu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tdu *TestDataUpdate) Exec(ctx context.Context) error {
	_, err := tdu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tdu *TestDataUpdate) ExecX(ctx context.Context) {
	if err := tdu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tdu *TestDataUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   testdata.Table,
			Columns: testdata.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: testdata.FieldID,
			},
		},
	}
	if ps := tdu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tdu.mutation.Text(); ok {
		_spec.SetField(testdata.FieldText, field.TypeString, value)
	}
	if value, ok := tdu.mutation.CreatedAt(); ok {
		_spec.SetField(testdata.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := tdu.mutation.UpdatedAt(); ok {
		_spec.SetField(testdata.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tdu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{testdata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// TestDataUpdateOne is the builder for updating a single TestData entity.
type TestDataUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TestDataMutation
}

// SetText sets the "text" field.
func (tduo *TestDataUpdateOne) SetText(s string) *TestDataUpdateOne {
	tduo.mutation.SetText(s)
	return tduo
}

// SetCreatedAt sets the "created_at" field.
func (tduo *TestDataUpdateOne) SetCreatedAt(t time.Time) *TestDataUpdateOne {
	tduo.mutation.SetCreatedAt(t)
	return tduo
}

// SetUpdatedAt sets the "updated_at" field.
func (tduo *TestDataUpdateOne) SetUpdatedAt(t time.Time) *TestDataUpdateOne {
	tduo.mutation.SetUpdatedAt(t)
	return tduo
}

// Mutation returns the TestDataMutation object of the builder.
func (tduo *TestDataUpdateOne) Mutation() *TestDataMutation {
	return tduo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tduo *TestDataUpdateOne) Select(field string, fields ...string) *TestDataUpdateOne {
	tduo.fields = append([]string{field}, fields...)
	return tduo
}

// Save executes the query and returns the updated TestData entity.
func (tduo *TestDataUpdateOne) Save(ctx context.Context) (*TestData, error) {
	var (
		err  error
		node *TestData
	)
	if len(tduo.hooks) == 0 {
		node, err = tduo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TestDataMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tduo.mutation = mutation
			node, err = tduo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tduo.hooks) - 1; i >= 0; i-- {
			if tduo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tduo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, tduo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*TestData)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from TestDataMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tduo *TestDataUpdateOne) SaveX(ctx context.Context) *TestData {
	node, err := tduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tduo *TestDataUpdateOne) Exec(ctx context.Context) error {
	_, err := tduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tduo *TestDataUpdateOne) ExecX(ctx context.Context) {
	if err := tduo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tduo *TestDataUpdateOne) sqlSave(ctx context.Context) (_node *TestData, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   testdata.Table,
			Columns: testdata.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: testdata.FieldID,
			},
		},
	}
	id, ok := tduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TestData.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, testdata.FieldID)
		for _, f := range fields {
			if !testdata.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != testdata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tduo.mutation.Text(); ok {
		_spec.SetField(testdata.FieldText, field.TypeString, value)
	}
	if value, ok := tduo.mutation.CreatedAt(); ok {
		_spec.SetField(testdata.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := tduo.mutation.UpdatedAt(); ok {
		_spec.SetField(testdata.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &TestData{config: tduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{testdata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
